name: freetimemaker-plc
adopt-info: freetimemaker-plc-part
base: core22
architectures:
  - build-on: [amd64]
    build-for: [all]
version: '1.0.2'
summary: Clicker but you click Programming Languages
description: |
  Like said in the summary, it's a Clicker Game where you have to click on Programming Languages.

grade: stable
confinement: classic

apps:
  freetimemaker-plc:
    command: desktop-launch $SNAP/usr/bin/com.freetimemaker.plc
    desktop: usr/share/apps/com.freetimemaker.plc.desktop
    plugs:
      - desktop
      - desktop-legacy

parts:
  freetimemaker-plc-part:
    plugin: meson
    meson-parameters: [--prefix=/snap/freetimemaker-plc/current/usr]
    override-pull: |
      craftctl pull

      # Point icon to the correct location
      sed -i.bak -e \
      's|Icon=com.freetimemaker.plc|Icon=/usr/share/icons/hicolor/scalable/apps/com.freetimemaker.plc.svg|g' \
      data/com.freetimemaker.plc.desktop.in