name: freetimemaker-plc
title: PLC 2.0
base: core22
version: '1.0.1'
summary: Clicker game with programming languages
description: |
  A clicker game where you click on programming languages.

grade: stable
confinement: strict # classic nicht erlaubt bei core22 ohne Review

architectures:
  - build-on: s390x
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
  - build-on: i386

apps:
  plc:
    command: PLC2.0.x86_64
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - opengl
      - joystick
      - audio-playback

parts:
  plc:
    plugin: dump
    source: snap/local
    override-build: |
      find . -name 'plc.desktop' -exec chmod 644 {} \;
      snapcraftctl build
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2
      - libflac8
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libasyncns0
      - libogg0
      - libpulse0
      - libsndfile1
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwebp7
