name: freetimemaker-plc
base: core24
version: '1.0.4'
summary: Clicker but you click Programming Languages
description: |
  Like said in the summary, it's a Clicker Game where you have to click on Programming Languages.

grade: stable
confinement: strict

parts:
  freetimemaker-plc:
    plugin: dump
    source: snap/local
    stage-packages:
      - libproxy1v5
      - glib-networking
      - libpulse0
    organize:
      freetimemaker-plc_Data/**: game/freetimemaker-plc_Data/
      bin/freetimemaker-plc.x86_64: game/freetimemaker-plc.x86_64
      bin/UnityPlayer.so: game/UnityPlayer.so
      share/applications/freetimemaker-plc.desktop: usr/share/applications/plc.desktop
      share/icons/hicolor/128x128/apps/freetimemaker-plc.png: meta/gui/plc.png

apps:
  freetimemaker-plc:
    command: game/freetimemaker-plc.x86_64
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: "$SNAP/freetimemaker-plc_Data/Plugins/x86_64:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
      GIO_EXTRA_MODULES: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gio/modules"
    plugs:
      - x11
      - opengl
      - network
      - network-bind
      - audio-playback
      - joystick
      - home
